# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('prediction_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('height', models.CharField(max_length=10)),
                ('H_L', models.CharField(max_length=10)),
                ('classification', models.CharField(max_length=25)),
                ('change', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Locations')),
            ],
        ),
    ]
